from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def test_storage_bridge_cloudbuild_config_uses_dedicated_dockerfile():
    text = (ROOT / "infra" / "cloudrun" / "cloudbuild.storage_bridge.yaml").read_text(encoding="utf-8")

    assert "gcr.io/cloud-builders/docker" in text
    assert "backend/Dockerfile.storage_bridge" in text
    assert "${_IMAGE_URI}" in text


def test_bootstrap_identity_script_no_longer_requires_preexisting_service_binding():
    text = (ROOT / "infra" / "cloudrun" / "bootstrap_prod_identity.sh").read_text(encoding="utf-8")

    assert "gcloud run services add-iam-policy-binding" not in text
    assert "gcloud services enable iap.googleapis.com" in text
    assert "roles/iap.httpsResourceAccessor" in text


def test_deploy_prod_script_binds_iap_service_agent_after_deploy_and_uses_control_plane_checks():
    text = (ROOT / "infra" / "cloudrun" / "deploy_prod.sh").read_text(encoding="utf-8")

    deploy_index = text.index('gcloud run deploy "${SERVICE_NAME}"')
    binding_index = text.index('gcloud run services add-iam-policy-binding "${SERVICE_NAME}"')
    assert deploy_index < binding_index
    assert 'grep -F "Iap Enabled: true"' in text
    assert 'TOKEN="$(gcloud auth print-identity-token' not in text


def test_storage_bridge_bootstrap_script_uses_cloudbuild_config_and_smoke_script():
    text = (ROOT / "infra" / "cloudrun" / "bootstrap_storage_bridge.sh").read_text(encoding="utf-8")

    assert "build_command_preview" in text
    assert "smoke_test_storage_bridge.sh" in text
    assert "gcloud secrets describe" in text


def test_runtime_lockfile_is_generated_with_python_312_baseline():
    text = (ROOT / "backend" / "requirements.runtime.lock.txt").read_text(encoding="utf-8")

    assert "autogenerated by pip-compile with Python 3.12" in text
