from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]


def test_storage_bridge_cloudbuild_config_uses_dedicated_dockerfile():
    text = (ROOT / "infra" / "cloudrun" / "cloudbuild.storage_bridge.yaml").read_text(encoding="utf-8")

    assert "gcr.io/cloud-builders/docker" in text
    assert "backend/Dockerfile.storage_bridge" in text
    assert "${_IMAGE_URI}" in text


def test_bootstrap_identity_script_no_longer_requires_preexisting_service_binding():
    text = (ROOT / "infra" / "cloudrun" / "bootstrap_prod_identity.sh").read_text(encoding="utf-8")

    assert "gcloud run services add-iam-policy-binding" not in text
    assert "gcloud services enable iap.googleapis.com" in text
    assert "roles/iap.httpsResourceAccessor" in text


def test_deploy_prod_script_binds_iap_service_agent_after_deploy_and_uses_control_plane_checks():
    text = (ROOT / "infra" / "cloudrun" / "deploy_prod.sh").read_text(encoding="utf-8")

    deploy_index = text.index('gcloud run deploy "${SERVICE_NAME}"')
    binding_index = text.index('gcloud run services add-iam-policy-binding "${SERVICE_NAME}"')
    assert deploy_index < binding_index
    assert 'grep -F "Iap Enabled: true"' in text
    assert 'TOKEN="$(gcloud auth print-identity-token' not in text


def test_storage_bridge_bootstrap_script_uses_cloudbuild_config_and_smoke_script():
    text = (ROOT / "infra" / "cloudrun" / "bootstrap_storage_bridge.sh").read_text(encoding="utf-8")

    assert "build_command_preview" in text
    assert "smoke_test_storage_bridge.sh" in text
    assert "gcloud secrets describe" in text


def test_storage_bridge_bootstrap_script_uses_two_phase_auth_bootstrap():
    text = (ROOT / "infra" / "cloudrun" / "bootstrap_storage_bridge.sh").read_text(encoding="utf-8")

    assert "BRIDGE_BOOTSTRAP_ALLOW_UNCONFIGURED_AUTH=1" in text
    assert 'lines.append(f"STORAGE_BRIDGE_AUTH_AUDIENCE={bridge_url}")' in text
    assert 'gcloud run services describe "${SERVICE_NAME}"' in text


def test_storage_bridge_smoke_test_uses_caller_service_account_impersonation():
    text = (ROOT / "infra" / "cloudrun" / "smoke_test_storage_bridge.sh").read_text(encoding="utf-8")

    assert '--impersonate-service-account="${CALLER_SERVICE_ACCOUNT}"' in text
    assert "roles/iam.serviceAccountTokenCreator" in text
    assert "gcloud iam service-accounts add-iam-policy-binding" in text


def test_no_pipe_plus_heredoc_python_stdin_conflicts_remain_in_cloudrun_scripts():
    pattern = re.compile(r"\|\s*python3\s+-[^\n]*<<['\"]PY['\"]")
    scripts = (
        ROOT / "infra" / "cloudrun" / "bootstrap_storage_bridge.sh",
        ROOT / "infra" / "cloudrun" / "smoke_test_storage_bridge.sh",
        ROOT / "infra" / "cloudrun" / "iam_policy_utils.sh",
    )

    for script in scripts:
        text = script.read_text(encoding="utf-8")
        assert pattern.search(text) is None, script.as_posix()


def test_bridge_invoker_binding_remains_scoped_to_bridge_service():
    text = (ROOT / "tools" / "validate_phase18_storage_bridge_bootstrap.py").read_text(encoding="utf-8")

    assert '"services"' in text
    assert 'config["service_name"]' in text
    assert "--role=roles/run.invoker" in text


def test_runtime_lockfile_is_generated_with_python_312_baseline():
    text = (ROOT / "backend" / "requirements.runtime.lock.txt").read_text(encoding="utf-8")

    assert "autogenerated by pip-compile with Python 3.12" in text
