"""initial_schema_runtime

Revision ID: 7ad763833b09
Revises: 
Create Date: 2026-08-20 16:43:29.944693
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '7ad763833b09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('external_email', sa.String(length=255), nullable=True),
    sa.Column('external_subject', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('external_email', name=op.f('uq_app_user_external_email')),
    sa.UniqueConstraint('external_subject', name=op.f('uq_app_user_external_subject')),
    sa.UniqueConstraint('username', name=op.f('uq_app_user_username'))
    )
    op.create_table('company',
    sa.Column('legacy_company_id', sa.Integer(), nullable=True),
    sa.Column('legacy_gmp_company_code', sa.String(length=32), nullable=True),
    sa.Column('legacy_glp_company_code', sa.String(length=32), nullable=True),
    sa.Column('legacy_gmpbb_company_code', sa.String(length=32), nullable=True),
    sa.Column('legal_name', sa.String(length=512), nullable=False),
    sa.Column('english_name', sa.String(length=512), nullable=True),
    sa.Column('short_name', sa.String(length=128), nullable=True),
    sa.Column('legal_address', sa.Text(), nullable=True),
    sa.Column('legal_address_en', sa.Text(), nullable=True),
    sa.Column('is_inactive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_company')),
    sa.UniqueConstraint('legacy_company_id', name=op.f('uq_company_legacy_company_id'))
    )
    op.create_table('dictionary_value',
    sa.Column('dictionary_name', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_en', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dictionary_value')),
    sa.UniqueConstraint('dictionary_name', 'key', name=op.f('uq_dictionary_value_dictionary_name'))
    )
    op.create_table('legacy_id_map',
    sa.Column('entity_type', sa.Enum('COMPANY', 'SITE', 'CASE', 'CERTIFICATE', 'BUSINESS_ELIGIBILITY', 'CHANGE_REQUEST', 'DOCUMENT', name='legacy_id_map_entity_type'), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=False),
    sa.Column('target_table', sa.String(length=128), nullable=False),
    sa.Column('target_entity_id', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legacy_id_map')),
    sa.UniqueConstraint('entity_type', 'legacy_id', name=op.f('uq_legacy_id_map_entity_type'))
    )
    op.create_table('migration_anomaly',
    sa.Column('source_sheet', sa.String(length=64), nullable=False),
    sa.Column('legacy_row_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('required_field', sa.String(length=128), nullable=True),
    sa.Column('raw_fk_value', sa.String(length=255), nullable=True),
    sa.Column('override_value', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_migration_anomaly'))
    )
    op.create_index(op.f('ix_migration_anomaly_legacy_row_id'), 'migration_anomaly', ['legacy_row_id'], unique=False)
    op.create_index(op.f('ix_migration_anomaly_reason'), 'migration_anomaly', ['reason'], unique=False)
    op.create_index(op.f('ix_migration_anomaly_source_sheet'), 'migration_anomaly', ['source_sheet'], unique=False)
    op.create_table('person',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_table('rbac_permission',
    sa.Column('permission_code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_permission')),
    sa.UniqueConstraint('permission_code', name=op.f('uq_rbac_permission_permission_code'))
    )
    op.create_table('rbac_role',
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_role')),
    sa.UniqueConstraint('role_code', name=op.f('uq_rbac_role_role_code'))
    )
    op.create_table('template_definition',
    sa.Column('family_code', sa.String(length=64), nullable=False),
    sa.Column('document_type_code', sa.String(length=64), nullable=False),
    sa.Column('source_application', sa.String(length=32), nullable=False),
    sa.Column('storage_scope', sa.String(length=32), nullable=False),
    sa.Column('legacy_host_procedure', sa.String(length=128), nullable=True),
    sa.Column('legacy_case_number', sa.Integer(), nullable=True),
    sa.Column('variant_type', sa.Enum('EDITABLE_DOCX', 'EDITABLE_XLSX', 'GENERATED_PDF', 'SCANNED_PDF', 'SIGNED_PDF', 'PRESENTATION_SOURCE', name='template_variant_type'), nullable=False),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('template_pattern', sa.String(length=255), nullable=True),
    sa.Column('bookmark_contract', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('template_storage_root', sa.String(length=32), nullable=True),
    sa.Column('template_storage_relative_path', sa.Text(), nullable=True),
    sa.Column('template_original_filename', sa.String(length=255), nullable=True),
    sa.Column('template_checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(template_storage_root IS NULL AND template_storage_relative_path IS NULL) OR (template_storage_root IS NOT NULL AND template_storage_relative_path IS NOT NULL)', name=op.f('ck_template_definition_template_definition_storage_locator_complete')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_definition')),
    sa.UniqueConstraint('family_code', 'template_name', name=op.f('uq_template_definition_family_code'))
    )
    op.create_index(op.f('ix_template_definition_document_type_code'), 'template_definition', ['document_type_code'], unique=False)
    op.create_index(op.f('ix_template_definition_family_code'), 'template_definition', ['family_code'], unique=False)
    op.create_table('app_user_role',
    sa.Column('app_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rbac_role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_user.id'], name=op.f('fk_app_user_role_app_user_id_app_user')),
    sa.ForeignKeyConstraint(['rbac_role_id'], ['rbac_role.id'], name=op.f('fk_app_user_role_rbac_role_id_rbac_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user_role')),
    sa.UniqueConstraint('app_user_id', 'rbac_role_id', name=op.f('uq_app_user_role_app_user_id'))
    )
    op.create_index(op.f('ix_app_user_role_app_user_id'), 'app_user_role', ['app_user_id'], unique=False)
    op.create_index(op.f('ix_app_user_role_rbac_role_id'), 'app_user_role', ['rbac_role_id'], unique=False)
    op.create_table('audit_event',
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'MIGRATION', name='audit_actor_type'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_fields_json', sa.Text(), nullable=True),
    sa.Column('old_values_json', sa.Text(), nullable=True),
    sa.Column('new_values_json', sa.Text(), nullable=True),
    sa.Column('payload_redacted', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_audit_event_actor_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index(op.f('ix_audit_event_actor_type'), 'audit_event', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_event_actor_user_id'), 'audit_event', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_event_request_id'), 'audit_event', ['request_id'], unique=False)
    op.create_table('current_projection_conflict',
    sa.Column('projection_type', sa.String(length=64), nullable=False),
    sa.Column('source_sheet', sa.String(length=64), nullable=False),
    sa.Column('business_key', sa.String(length=128), nullable=False),
    sa.Column('classification', sa.String(length=128), nullable=False),
    sa.Column('resolution_policy', sa.String(length=64), server_default='manual_review_required', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='open', nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('adjudicated_on', sa.Date(), nullable=True),
    sa.Column('adjudicated_by_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('candidate_legacy_ids_json', sa.Text(), nullable=False),
    sa.Column('adjudication_payload_json', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['adjudicated_by_user_id'], ['app_user.id'], name=op.f('fk_current_projection_conflict_adjudicated_by_user_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_current_projection_conflict')),
    sa.UniqueConstraint('projection_type', 'source_sheet', 'business_key', name='uq_current_projection_conflict_open_key')
    )
    op.create_index(op.f('ix_current_projection_conflict_adjudicated_by_user_id'), 'current_projection_conflict', ['adjudicated_by_user_id'], unique=False)
    op.create_index(op.f('ix_current_projection_conflict_business_key'), 'current_projection_conflict', ['business_key'], unique=False)
    op.create_index(op.f('ix_current_projection_conflict_classification'), 'current_projection_conflict', ['classification'], unique=False)
    op.create_index(op.f('ix_current_projection_conflict_projection_type'), 'current_projection_conflict', ['projection_type'], unique=False)
    op.create_index(op.f('ix_current_projection_conflict_source_sheet'), 'current_projection_conflict', ['source_sheet'], unique=False)
    op.create_table('inspector_profile',
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('legacy_initials', sa.String(length=32), nullable=True),
    sa.Column('legacy_display_text', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_inspector_profile_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspector_profile')),
    sa.UniqueConstraint('person_id', name=op.f('uq_inspector_profile_person_id'))
    )
    op.create_table('professional_license',
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('license_number', sa.String(length=128), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_professional_license_person_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_license'))
    )
    op.create_index(op.f('ix_professional_license_person_id'), 'professional_license', ['person_id'], unique=False)
    op.create_table('rbac_role_permission',
    sa.Column('rbac_role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('rbac_permission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rbac_permission_id'], ['rbac_permission.id'], name=op.f('fk_rbac_role_permission_rbac_permission_id_rbac_permission')),
    sa.ForeignKeyConstraint(['rbac_role_id'], ['rbac_role.id'], name=op.f('fk_rbac_role_permission_rbac_role_id_rbac_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_role_permission')),
    sa.UniqueConstraint('rbac_role_id', 'rbac_permission_id', name=op.f('uq_rbac_role_permission_rbac_role_id'))
    )
    op.create_index(op.f('ix_rbac_role_permission_rbac_permission_id'), 'rbac_role_permission', ['rbac_permission_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permission_rbac_role_id'), 'rbac_role_permission', ['rbac_role_id'], unique=False)
    op.create_table('site',
    sa.Column('legacy_site_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('legacy_gmp_site_code', sa.String(length=32), nullable=True),
    sa.Column('legacy_glp_site_code', sa.String(length=32), nullable=True),
    sa.Column('legacy_gmpbb_site_code', sa.String(length=32), nullable=True),
    sa.Column('site_name', sa.String(length=512), nullable=False),
    sa.Column('site_name_en', sa.String(length=512), nullable=True),
    sa.Column('site_address', sa.Text(), nullable=True),
    sa.Column('site_address_en', sa.Text(), nullable=True),
    sa.Column('province_name', sa.String(length=255), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_site_company_id_company')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site')),
    sa.UniqueConstraint('legacy_site_id', name=op.f('uq_site_legacy_site_id'))
    )
    op.create_index(op.f('ix_site_company_id'), 'site', ['company_id'], unique=False)
    op.create_table('template_binding',
    sa.Column('family_code', sa.String(length=64), nullable=False),
    sa.Column('template_definition_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gxp_type', sa.String(length=32), nullable=True),
    sa.Column('legacy_mode', sa.String(length=64), nullable=True),
    sa.Column('storage_scope', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_definition_id'], ['template_definition.id'], name=op.f('fk_template_binding_template_definition_id_template_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_binding')),
    sa.UniqueConstraint('family_code', 'template_definition_id', 'gxp_type', 'legacy_mode', 'storage_scope', name=op.f('uq_template_binding_family_code'))
    )
    op.create_index(op.f('ix_template_binding_family_code'), 'template_binding', ['family_code'], unique=False)
    op.create_index(op.f('ix_template_binding_gxp_type'), 'template_binding', ['gxp_type'], unique=False)
    op.create_index(op.f('ix_template_binding_legacy_mode'), 'template_binding', ['legacy_mode'], unique=False)
    op.create_index(op.f('ix_template_binding_template_definition_id'), 'template_binding', ['template_definition_id'], unique=False)
    op.create_table('business_eligibility_certificate',
    sa.Column('legacy_dkkd_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('company_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('latest_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latest_legacy_dkkd_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('fk_business_eligibility_certificate_company_id_company')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_business_eligibility_certificate_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_eligibility_certificate')),
    sa.UniqueConstraint('legacy_dkkd_id', name=op.f('uq_business_eligibility_certificate_legacy_dkkd_id'))
    )
    op.create_index(op.f('ix_business_eligibility_certificate_company_id'), 'business_eligibility_certificate', ['company_id'], unique=False)
    op.create_index(op.f('ix_business_eligibility_certificate_site_id'), 'business_eligibility_certificate', ['site_id'], unique=False)
    op.create_table('case',
    sa.Column('legacy_inspection_id', sa.Integer(), nullable=True),
    sa.Column('legacy_inspection_code', sa.String(length=64), nullable=True),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gxp_type', sa.String(length=32), nullable=False),
    sa.Column('scope_code', sa.String(length=32), nullable=True),
    sa.Column('applicable_standard', sa.String(length=255), nullable=True),
    sa.Column('inspection_type', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('DRAFT', 'APPLICATION_RECEIVED', 'UNDER_ASSESSMENT', 'PLANNED', 'DECISION_ISSUED', 'INSPECTION_IN_PROGRESS', 'INSPECTION_COMPLETED', 'AWAITING_CERTIFICATE_DECISION', 'CERTIFIED', 'CLOSED', 'CANCELLED', name='case_state'), nullable=False),
    sa.Column('opened_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_case_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case')),
    sa.UniqueConstraint('legacy_inspection_id', name=op.f('uq_case_legacy_inspection_id'))
    )
    op.create_index(op.f('ix_case_legacy_inspection_code'), 'case', ['legacy_inspection_code'], unique=False)
    op.create_index(op.f('ix_case_site_id'), 'case', ['site_id'], unique=False)
    op.create_index('ix_case_site_state', 'case', ['site_id', 'state'], unique=False)
    op.create_index(op.f('ix_case_state'), 'case', ['state'], unique=False)
    op.create_table('change_request',
    sa.Column('legacy_change_request_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope_label', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submitted_on', sa.Date(), nullable=True),
    sa.Column('requester_name', sa.String(length=255), nullable=True),
    sa.Column('state', sa.Enum('RECEIVED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'EFFECTIVE', 'SUPERSEDED', name='change_request_state'), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_change_request_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_request')),
    sa.UniqueConstraint('legacy_change_request_id', name=op.f('uq_change_request_legacy_change_request_id'))
    )
    op.create_index(op.f('ix_change_request_site_id'), 'change_request', ['site_id'], unique=False)
    op.create_index(op.f('ix_change_request_state'), 'change_request', ['state'], unique=False)
    op.create_table('person_role',
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('role_name', sa.String(length=128), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_person_role_person_id_person')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_person_role_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_role'))
    )
    op.create_index(op.f('ix_person_role_person_id'), 'person_role', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_role_site_id'), 'person_role', ['site_id'], unique=False)
    op.create_table('business_eligibility_version',
    sa.Column('business_eligibility_certificate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('certificate_number', sa.String(length=128), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('professional_responsible_person_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['business_eligibility_certificate_id'], ['business_eligibility_certificate.id'], name=op.f('fk_business_eligibility_version_business_eligibility_certificate_id_business_eligibility_certificate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_eligibility_version')),
    sa.UniqueConstraint('business_eligibility_certificate_id', 'version_no', name=op.f('uq_business_eligibility_version_business_eligibility_certificate_id'))
    )
    op.create_index(op.f('ix_business_eligibility_version_business_eligibility_certificate_id'), 'business_eligibility_version', ['business_eligibility_certificate_id'], unique=False)
    op.create_table('capa_cycle',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('requested_on', sa.Date(), nullable=True),
    sa.Column('submitted_on', sa.Date(), nullable=True),
    sa.Column('assessed_on', sa.Date(), nullable=True),
    sa.Column('assessor_name', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=64), server_default='draft', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_capa_cycle_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capa_cycle')),
    sa.UniqueConstraint('case_id', 'round_no', name=op.f('uq_capa_cycle_case_id'))
    )
    op.create_index(op.f('ix_capa_cycle_case_id'), 'capa_cycle', ['case_id'], unique=False)
    op.create_table('case_application',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('submitted_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dossier_code', sa.String(length=128), nullable=True),
    sa.Column('dossier_reference', sa.Text(), nullable=True),
    sa.Column('applicant_name', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_case_application_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_application')),
    sa.UniqueConstraint('case_id', name=op.f('uq_case_application_case_id'))
    )
    op.create_table('case_assessment',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('assessed_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assessor_name', sa.String(length=255), nullable=True),
    sa.Column('assessment_result', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_case_assessment_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_assessment')),
    sa.UniqueConstraint('case_id', name=op.f('uq_case_assessment_case_id'))
    )
    op.create_table('certificate',
    sa.Column('legacy_certificate_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('site_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('certificate_type', sa.String(length=32), nullable=False),
    sa.Column('issuance_basis', sa.String(length=64), server_default='inspection_case', nullable=False),
    sa.Column('latest_flag', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('latest_legacy_certificate_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_certificate_case_id_case')),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], name=op.f('fk_certificate_site_id_site')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate')),
    sa.UniqueConstraint('legacy_certificate_id', name=op.f('uq_certificate_legacy_certificate_id'))
    )
    op.create_index(op.f('ix_certificate_case_id'), 'certificate', ['case_id'], unique=False)
    op.create_index('ix_certificate_case_type', 'certificate', ['case_id', 'certificate_type'], unique=False)
    op.create_index(op.f('ix_certificate_site_id'), 'certificate', ['site_id'], unique=False)
    op.create_table('change_approval',
    sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('handled_on', sa.Date(), nullable=True),
    sa.Column('handled_by_name', sa.String(length=255), nullable=True),
    sa.Column('result_label', sa.String(length=255), nullable=True),
    sa.Column('effective_on', sa.Date(), nullable=True),
    sa.Column('approval_reference', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_request.id'], name=op.f('fk_change_approval_change_request_id_change_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_approval')),
    sa.UniqueConstraint('change_request_id', name=op.f('uq_change_approval_change_request_id'))
    )
    op.create_table('change_request_detail',
    sa.Column('legacy_change_detail_id', sa.Integer(), nullable=True),
    sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=True),
    sa.Column('classification_label', sa.String(length=255), nullable=True),
    sa.Column('approval_status', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_request.id'], name=op.f('fk_change_request_detail_change_request_id_change_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_request_detail')),
    sa.UniqueConstraint('legacy_change_detail_id', name=op.f('uq_change_request_detail_legacy_change_detail_id'))
    )
    op.create_index(op.f('ix_change_request_detail_change_request_id'), 'change_request_detail', ['change_request_id'], unique=False)
    op.create_table('inspection_event',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Enum('APPLICATION_SUBMITTED', 'ASSESSMENT_COMPLETED', 'PLAN_CREATED', 'DECISION_ISSUED', 'INSPECTION_EXECUTED', 'OUTCOME_RECORDED', 'CERTIFICATE_ISSUED', name='inspection_event_type'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_inspection_event_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_event'))
    )
    op.create_index(op.f('ix_inspection_event_case_id'), 'inspection_event', ['case_id'], unique=False)
    op.create_index(op.f('ix_inspection_event_event_type'), 'inspection_event', ['event_type'], unique=False)
    op.create_table('inspection_outcome',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('inspected_on', sa.Date(), nullable=True),
    sa.Column('inspected_to_on', sa.Date(), nullable=True),
    sa.Column('decision_reference', sa.String(length=255), nullable=True),
    sa.Column('bbkt_reference', sa.String(length=255), nullable=True),
    sa.Column('outcome_result', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_inspection_outcome_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_outcome')),
    sa.UniqueConstraint('case_id', name=op.f('uq_inspection_outcome_case_id'))
    )
    op.create_table('inspection_plan',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_start_on', sa.Date(), nullable=True),
    sa.Column('plan_end_on', sa.Date(), nullable=True),
    sa.Column('planning_sheet_name', sa.String(length=64), nullable=True),
    sa.Column('decision_document_hint', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_inspection_plan_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_plan')),
    sa.UniqueConstraint('case_id', name=op.f('uq_inspection_plan_case_id'))
    )
    op.create_table('inspection_team',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('display_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_inspection_team_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_team')),
    sa.UniqueConstraint('case_id', name=op.f('uq_inspection_team_case_id'))
    )
    op.create_table('storage_binding',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('site_legacy_id', sa.Integer(), nullable=True),
    sa.Column('inspection_legacy_code', sa.String(length=64), nullable=True),
    sa.Column('relative_path', sa.Text(), nullable=False),
    sa.Column('observed_folder_label', sa.String(length=512), nullable=True),
    sa.Column('storage_class', sa.String(length=64), server_default='synology_legacy', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(year IS NULL AND site_legacy_id IS NULL AND inspection_legacy_code IS NULL) OR (year IS NOT NULL AND site_legacy_id IS NOT NULL AND inspection_legacy_code IS NOT NULL)', name=op.f('ck_storage_binding_storage_binding_key_triplet_complete')),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_storage_binding_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_binding')),
    sa.UniqueConstraint('year', 'site_legacy_id', 'inspection_legacy_code', name=op.f('uq_storage_binding_year'))
    )
    op.create_index(op.f('ix_storage_binding_case_id'), 'storage_binding', ['case_id'], unique=False)
    op.create_table('storage_resolution_log',
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('site_legacy_id', sa.Integer(), nullable=True),
    sa.Column('inspection_legacy_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('RESOLVED', 'NOT_FOUND', 'AMBIGUOUS', 'INVALID', name='storage_resolution_status'), nullable=False),
    sa.Column('candidate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resolved_relative_path', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_storage_resolution_log_case_id_case')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_resolution_log'))
    )
    op.create_index(op.f('ix_storage_resolution_log_case_id'), 'storage_resolution_log', ['case_id'], unique=False)
    op.create_index(op.f('ix_storage_resolution_log_status'), 'storage_resolution_log', ['status'], unique=False)
    op.create_index('ix_storage_resolution_lookup', 'storage_resolution_log', ['year', 'site_legacy_id', 'inspection_legacy_code'], unique=False)
    op.create_table('business_eligibility_certificate_link',
    sa.Column('business_eligibility_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('certificate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('link_role', sa.String(length=64), server_default='source_certificate', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['business_eligibility_version_id'], ['business_eligibility_version.id'], name=op.f('fk_business_eligibility_certificate_link_business_eligibility_version_id_business_eligibility_version')),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], name=op.f('fk_business_eligibility_certificate_link_certificate_id_certificate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_eligibility_certificate_link')),
    sa.UniqueConstraint('business_eligibility_version_id', 'certificate_id', name=op.f('uq_business_eligibility_certificate_link_business_eligibility_version_id'))
    )
    op.create_index(op.f('ix_business_eligibility_certificate_link_business_eligibility_version_id'), 'business_eligibility_certificate_link', ['business_eligibility_version_id'], unique=False)
    op.create_index(op.f('ix_business_eligibility_certificate_link_certificate_id'), 'business_eligibility_certificate_link', ['certificate_id'], unique=False)
    op.create_table('certificate_version',
    sa.Column('certificate_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('certificate_number', sa.String(length=128), nullable=True),
    sa.Column('is_latest_version', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], name=op.f('fk_certificate_version_certificate_id_certificate')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate_version')),
    sa.UniqueConstraint('certificate_id', 'version_no', name=op.f('uq_certificate_version_certificate_id'))
    )
    op.create_index(op.f('ix_certificate_version_certificate_id'), 'certificate_version', ['certificate_id'], unique=False)
    op.create_table('document',
    sa.Column('legacy_entity_type', sa.Enum('COMPANY', 'SITE', 'CASE', 'CERTIFICATE', 'BUSINESS_ELIGIBILITY', 'CHANGE_REQUEST', 'DOCUMENT', name='legacy_entity_type'), nullable=True),
    sa.Column('family_code', sa.String(length=64), nullable=False),
    sa.Column('document_type_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('case_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('capa_cycle_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('certificate_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('business_eligibility_certificate_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('change_request_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(case_id IS NOT NULL) OR (capa_cycle_id IS NOT NULL) OR (certificate_id IS NOT NULL) OR (business_eligibility_certificate_id IS NOT NULL) OR (change_request_id IS NOT NULL)', name=op.f('ck_document_document_has_parent')),
    sa.ForeignKeyConstraint(['business_eligibility_certificate_id'], ['business_eligibility_certificate.id'], name=op.f('fk_document_business_eligibility_certificate_id_business_eligibility_certificate')),
    sa.ForeignKeyConstraint(['capa_cycle_id'], ['capa_cycle.id'], name=op.f('fk_document_capa_cycle_id_capa_cycle')),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], name=op.f('fk_document_case_id_case')),
    sa.ForeignKeyConstraint(['certificate_id'], ['certificate.id'], name=op.f('fk_document_certificate_id_certificate')),
    sa.ForeignKeyConstraint(['change_request_id'], ['change_request.id'], name=op.f('fk_document_change_request_id_change_request')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_business_eligibility_certificate_id'), 'document', ['business_eligibility_certificate_id'], unique=False)
    op.create_index(op.f('ix_document_capa_cycle_id'), 'document', ['capa_cycle_id'], unique=False)
    op.create_index(op.f('ix_document_case_id'), 'document', ['case_id'], unique=False)
    op.create_index(op.f('ix_document_certificate_id'), 'document', ['certificate_id'], unique=False)
    op.create_index(op.f('ix_document_change_request_id'), 'document', ['change_request_id'], unique=False)
    op.create_index(op.f('ix_document_family_code'), 'document', ['family_code'], unique=False)
    op.create_table('inspection_team_member',
    sa.Column('team_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('inspector_profile_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('person_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('role_label', sa.String(length=128), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('inspector_profile_id IS NOT NULL OR person_id IS NOT NULL', name=op.f('ck_inspection_team_member_team_member_has_identity')),
    sa.ForeignKeyConstraint(['inspector_profile_id'], ['inspector_profile.id'], name=op.f('fk_inspection_team_member_inspector_profile_id_inspector_profile')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_inspection_team_member_person_id_person')),
    sa.ForeignKeyConstraint(['team_id'], ['inspection_team.id'], name=op.f('fk_inspection_team_member_team_id_inspection_team')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspection_team_member'))
    )
    op.create_index(op.f('ix_inspection_team_member_inspector_profile_id'), 'inspection_team_member', ['inspector_profile_id'], unique=False)
    op.create_index(op.f('ix_inspection_team_member_person_id'), 'inspection_team_member', ['person_id'], unique=False)
    op.create_index(op.f('ix_inspection_team_member_team_id'), 'inspection_team_member', ['team_id'], unique=False)
    op.create_table('certificate_scope',
    sa.Column('certificate_version_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope_key', sa.String(length=128), nullable=True),
    sa.Column('scope_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=8), server_default='vi', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['certificate_version_id'], ['certificate_version.id'], name=op.f('fk_certificate_scope_certificate_version_id_certificate_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certificate_scope'))
    )
    op.create_index(op.f('ix_certificate_scope_certificate_version_id'), 'certificate_scope', ['certificate_version_id'], unique=False)
    op.create_table('document_relation',
    sa.Column('source_document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_document_id <> target_document_id', name=op.f('ck_document_relation_document_relation_not_self')),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], name=op.f('fk_document_relation_source_document_id_document')),
    sa.ForeignKeyConstraint(['target_document_id'], ['document.id'], name=op.f('fk_document_relation_target_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_relation')),
    sa.UniqueConstraint('source_document_id', 'target_document_id', 'relation_type', name=op.f('uq_document_relation_source_document_id'))
    )
    op.create_index(op.f('ix_document_relation_source_document_id'), 'document_relation', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_relation_target_document_id'), 'document_relation', ['target_document_id'], unique=False)
    op.create_table('document_variant',
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('variant_type', sa.Enum('EDITABLE_DOCX', 'EDITABLE_XLSX', 'GENERATED_PDF', 'SCANNED_PDF', 'SIGNED_PDF', 'PRESENTATION_SOURCE', name='document_variant_type'), nullable=False),
    sa.Column('language_code', sa.String(length=8), server_default='vi', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_variant_document_id_document')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_variant')),
    sa.UniqueConstraint('document_id', 'variant_type', 'language_code', name=op.f('uq_document_variant_document_id'))
    )
    op.create_index(op.f('ix_document_variant_document_id'), 'document_variant', ['document_id'], unique=False)
    op.create_table('document_version',
    sa.Column('document_variant_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('storage_binding_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('storage_root', sa.String(length=32), nullable=True),
    sa.Column('storage_relative_path', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('issued_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('(storage_root IS NULL AND storage_relative_path IS NULL) OR (storage_root IS NOT NULL AND storage_relative_path IS NOT NULL)', name=op.f('ck_document_version_document_version_storage_locator_complete')),
    sa.ForeignKeyConstraint(['document_variant_id'], ['document_variant.id'], name=op.f('fk_document_version_document_variant_id_document_variant')),
    sa.ForeignKeyConstraint(['storage_binding_id'], ['storage_binding.id'], name=op.f('fk_document_version_storage_binding_id_storage_binding')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_version')),
    sa.UniqueConstraint('document_variant_id', 'version_no', name=op.f('uq_document_version_document_variant_id'))
    )
    op.create_index(op.f('ix_document_version_document_variant_id'), 'document_version', ['document_variant_id'], unique=False)
    op.create_index(op.f('ix_document_version_storage_binding_id'), 'document_version', ['storage_binding_id'], unique=False)
    op.create_table('document_generation_run',
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('template_binding_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('template_definition_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('output_document_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELLED', name='document_generation_status'), nullable=False),
    sa.Column('source_application', sa.String(length=32), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('input_payload_redacted', sa.Text(), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_generation_run_document_id_document')),
    sa.ForeignKeyConstraint(['output_document_version_id'], ['document_version.id'], name=op.f('fk_document_generation_run_output_document_version_id_document_version')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['app_user.id'], name=op.f('fk_document_generation_run_requested_by_user_id_app_user')),
    sa.ForeignKeyConstraint(['template_binding_id'], ['template_binding.id'], name=op.f('fk_document_generation_run_template_binding_id_template_binding')),
    sa.ForeignKeyConstraint(['template_definition_id'], ['template_definition.id'], name=op.f('fk_document_generation_run_template_definition_id_template_definition')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_generation_run')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_document_generation_run_idempotency_key'))
    )
    op.create_index(op.f('ix_document_generation_run_document_id'), 'document_generation_run', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_generation_run_output_document_version_id'), 'document_generation_run', ['output_document_version_id'], unique=False)
    op.create_index(op.f('ix_document_generation_run_requested_by_user_id'), 'document_generation_run', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_document_generation_run_status'), 'document_generation_run', ['status'], unique=False)
    op.create_index(op.f('ix_document_generation_run_template_binding_id'), 'document_generation_run', ['template_binding_id'], unique=False)
    op.create_index(op.f('ix_document_generation_run_template_definition_id'), 'document_generation_run', ['template_definition_id'], unique=False)
    op.create_table('document_source_dependency',
    sa.Column('document_generation_run_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_document_version_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('dependency_type', sa.String(length=64), nullable=False),
    sa.Column('source_bookmarks', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_generation_run_id'], ['document_generation_run.id'], name=op.f('fk_document_source_dependency_document_generation_run_id_document_generation_run')),
    sa.ForeignKeyConstraint(['source_document_id'], ['document.id'], name=op.f('fk_document_source_dependency_source_document_id_document')),
    sa.ForeignKeyConstraint(['source_document_version_id'], ['document_version.id'], name=op.f('fk_document_source_dependency_source_document_version_id_document_version')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_source_dependency')),
    sa.UniqueConstraint('document_generation_run_id', 'source_document_id', 'source_document_version_id', 'dependency_type', name=op.f('uq_document_source_dependency_document_generation_run_id'))
    )
    op.create_index(op.f('ix_document_source_dependency_document_generation_run_id'), 'document_source_dependency', ['document_generation_run_id'], unique=False)
    op.create_index(op.f('ix_document_source_dependency_source_document_id'), 'document_source_dependency', ['source_document_id'], unique=False)
    op.create_index(op.f('ix_document_source_dependency_source_document_version_id'), 'document_source_dependency', ['source_document_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_source_dependency_source_document_version_id'), table_name='document_source_dependency')
    op.drop_index(op.f('ix_document_source_dependency_source_document_id'), table_name='document_source_dependency')
    op.drop_index(op.f('ix_document_source_dependency_document_generation_run_id'), table_name='document_source_dependency')
    op.drop_table('document_source_dependency')
    op.drop_index(op.f('ix_document_generation_run_template_definition_id'), table_name='document_generation_run')
    op.drop_index(op.f('ix_document_generation_run_template_binding_id'), table_name='document_generation_run')
    op.drop_index(op.f('ix_document_generation_run_status'), table_name='document_generation_run')
    op.drop_index(op.f('ix_document_generation_run_requested_by_user_id'), table_name='document_generation_run')
    op.drop_index(op.f('ix_document_generation_run_output_document_version_id'), table_name='document_generation_run')
    op.drop_index(op.f('ix_document_generation_run_document_id'), table_name='document_generation_run')
    op.drop_table('document_generation_run')
    op.drop_index(op.f('ix_document_version_storage_binding_id'), table_name='document_version')
    op.drop_index(op.f('ix_document_version_document_variant_id'), table_name='document_version')
    op.drop_table('document_version')
    op.drop_index(op.f('ix_document_variant_document_id'), table_name='document_variant')
    op.drop_table('document_variant')
    op.drop_index(op.f('ix_document_relation_target_document_id'), table_name='document_relation')
    op.drop_index(op.f('ix_document_relation_source_document_id'), table_name='document_relation')
    op.drop_table('document_relation')
    op.drop_index(op.f('ix_certificate_scope_certificate_version_id'), table_name='certificate_scope')
    op.drop_table('certificate_scope')
    op.drop_index(op.f('ix_inspection_team_member_team_id'), table_name='inspection_team_member')
    op.drop_index(op.f('ix_inspection_team_member_person_id'), table_name='inspection_team_member')
    op.drop_index(op.f('ix_inspection_team_member_inspector_profile_id'), table_name='inspection_team_member')
    op.drop_table('inspection_team_member')
    op.drop_index(op.f('ix_document_family_code'), table_name='document')
    op.drop_index(op.f('ix_document_change_request_id'), table_name='document')
    op.drop_index(op.f('ix_document_certificate_id'), table_name='document')
    op.drop_index(op.f('ix_document_case_id'), table_name='document')
    op.drop_index(op.f('ix_document_capa_cycle_id'), table_name='document')
    op.drop_index(op.f('ix_document_business_eligibility_certificate_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_certificate_version_certificate_id'), table_name='certificate_version')
    op.drop_table('certificate_version')
    op.drop_index(op.f('ix_business_eligibility_certificate_link_certificate_id'), table_name='business_eligibility_certificate_link')
    op.drop_index(op.f('ix_business_eligibility_certificate_link_business_eligibility_version_id'), table_name='business_eligibility_certificate_link')
    op.drop_table('business_eligibility_certificate_link')
    op.drop_index('ix_storage_resolution_lookup', table_name='storage_resolution_log')
    op.drop_index(op.f('ix_storage_resolution_log_status'), table_name='storage_resolution_log')
    op.drop_index(op.f('ix_storage_resolution_log_case_id'), table_name='storage_resolution_log')
    op.drop_table('storage_resolution_log')
    op.drop_index(op.f('ix_storage_binding_case_id'), table_name='storage_binding')
    op.drop_table('storage_binding')
    op.drop_table('inspection_team')
    op.drop_table('inspection_plan')
    op.drop_table('inspection_outcome')
    op.drop_index(op.f('ix_inspection_event_event_type'), table_name='inspection_event')
    op.drop_index(op.f('ix_inspection_event_case_id'), table_name='inspection_event')
    op.drop_table('inspection_event')
    op.drop_index(op.f('ix_change_request_detail_change_request_id'), table_name='change_request_detail')
    op.drop_table('change_request_detail')
    op.drop_table('change_approval')
    op.drop_index(op.f('ix_certificate_site_id'), table_name='certificate')
    op.drop_index('ix_certificate_case_type', table_name='certificate')
    op.drop_index(op.f('ix_certificate_case_id'), table_name='certificate')
    op.drop_table('certificate')
    op.drop_table('case_assessment')
    op.drop_table('case_application')
    op.drop_index(op.f('ix_capa_cycle_case_id'), table_name='capa_cycle')
    op.drop_table('capa_cycle')
    op.drop_index(op.f('ix_business_eligibility_version_business_eligibility_certificate_id'), table_name='business_eligibility_version')
    op.drop_table('business_eligibility_version')
    op.drop_index(op.f('ix_person_role_site_id'), table_name='person_role')
    op.drop_index(op.f('ix_person_role_person_id'), table_name='person_role')
    op.drop_table('person_role')
    op.drop_index(op.f('ix_change_request_state'), table_name='change_request')
    op.drop_index(op.f('ix_change_request_site_id'), table_name='change_request')
    op.drop_table('change_request')
    op.drop_index(op.f('ix_case_state'), table_name='case')
    op.drop_index('ix_case_site_state', table_name='case')
    op.drop_index(op.f('ix_case_site_id'), table_name='case')
    op.drop_index(op.f('ix_case_legacy_inspection_code'), table_name='case')
    op.drop_table('case')
    op.drop_index(op.f('ix_business_eligibility_certificate_site_id'), table_name='business_eligibility_certificate')
    op.drop_index(op.f('ix_business_eligibility_certificate_company_id'), table_name='business_eligibility_certificate')
    op.drop_table('business_eligibility_certificate')
    op.drop_index(op.f('ix_template_binding_template_definition_id'), table_name='template_binding')
    op.drop_index(op.f('ix_template_binding_legacy_mode'), table_name='template_binding')
    op.drop_index(op.f('ix_template_binding_gxp_type'), table_name='template_binding')
    op.drop_index(op.f('ix_template_binding_family_code'), table_name='template_binding')
    op.drop_table('template_binding')
    op.drop_index(op.f('ix_site_company_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_rbac_role_permission_rbac_role_id'), table_name='rbac_role_permission')
    op.drop_index(op.f('ix_rbac_role_permission_rbac_permission_id'), table_name='rbac_role_permission')
    op.drop_table('rbac_role_permission')
    op.drop_index(op.f('ix_professional_license_person_id'), table_name='professional_license')
    op.drop_table('professional_license')
    op.drop_table('inspector_profile')
    op.drop_index(op.f('ix_current_projection_conflict_source_sheet'), table_name='current_projection_conflict')
    op.drop_index(op.f('ix_current_projection_conflict_projection_type'), table_name='current_projection_conflict')
    op.drop_index(op.f('ix_current_projection_conflict_classification'), table_name='current_projection_conflict')
    op.drop_index(op.f('ix_current_projection_conflict_business_key'), table_name='current_projection_conflict')
    op.drop_index(op.f('ix_current_projection_conflict_adjudicated_by_user_id'), table_name='current_projection_conflict')
    op.drop_table('current_projection_conflict')
    op.drop_index(op.f('ix_audit_event_request_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_user_id'), table_name='audit_event')
    op.drop_index(op.f('ix_audit_event_actor_type'), table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_index(op.f('ix_app_user_role_rbac_role_id'), table_name='app_user_role')
    op.drop_index(op.f('ix_app_user_role_app_user_id'), table_name='app_user_role')
    op.drop_table('app_user_role')
    op.drop_index(op.f('ix_template_definition_family_code'), table_name='template_definition')
    op.drop_index(op.f('ix_template_definition_document_type_code'), table_name='template_definition')
    op.drop_table('template_definition')
    op.drop_table('rbac_role')
    op.drop_table('rbac_permission')
    op.drop_table('person')
    op.drop_index(op.f('ix_migration_anomaly_source_sheet'), table_name='migration_anomaly')
    op.drop_index(op.f('ix_migration_anomaly_reason'), table_name='migration_anomaly')
    op.drop_index(op.f('ix_migration_anomaly_legacy_row_id'), table_name='migration_anomaly')
    op.drop_table('migration_anomaly')
    op.drop_table('legacy_id_map')
    op.drop_table('dictionary_value')
    op.drop_table('company')
    op.drop_table('app_user')
    # ### end Alembic commands ###
