from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PHASE5_DIR = ROOT / "artifacts" / "phase5"
AUDIT_PATH = PHASE5_DIR / "template_compatibility_audit.json"
RECON_PATH = PHASE5_DIR / "template_contract_reconciled.json"
DDKD_VARIANTS_PATH = PHASE5_DIR / "dkkd_template_variants.json"
BBTD_VARIANTS_PATH = PHASE5_DIR / "bbtd_template_variants.json"
DDKD_APPENDIX_PATH = PHASE5_DIR / "ddkd_appendix_field_adjudication.json"
JSON_OUT = PHASE5_DIR / "phase5_final_closeout.json"
MD_OUT = PHASE5_DIR / "phase5_final_closeout.md"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def build_summary() -> dict[str, Any]:
    audit = load_json(AUDIT_PATH)
    reconciled = load_json(RECON_PATH)
    dkkd_variants = load_json(DDKD_VARIANTS_PATH)
    bbtd_variants = load_json(BBTD_VARIANTS_PATH)
    appendix = load_json(DDKD_APPENDIX_PATH)

    family_codes = [item["family_code"] for item in reconciled["families"]]
    contract_exact_scalar = [
        "INSPECTION_CAPA_LAN_1",
        "INSPECTION_CAPA_LAN_2",
    ]
    contract_variant_exact = [
        "DDKD_CERTIFICATE",
        "INSPECTION_BBTD_HOSO_DK",
    ]
    selection_safe = ["DDKD_APPENDIX_OR_DECISION"]
    promoted = set(contract_exact_scalar) | set(contract_variant_exact) | set(selection_safe)
    payload_passthrough_remaining = sorted(code for code in family_codes if code not in promoted)

    blocked_fields = appendix.get("recommended_next_state", {}).get("still_blocked", [])
    promotable_now = appendix.get("recommended_next_state", {}).get("promotable_now", [])

    return {
        "generated_on": "2026-08-14",
        "phase5_status": "closed",
        "document_generation_baseline": {
            "registry_family_count": audit.get("registry_family_count", 0),
            "matched_family_count": audit.get("matched_family_count", 0),
            "active_template_file_count": audit.get("active_file_count", 0),
            "powerpoint_branch_in_scope": False,
        },
        "runtime_contract_status": {
            "contract_exact_scalar_families": contract_exact_scalar,
            "contract_variant_exact_families": contract_variant_exact,
            "selection_safe_families": selection_safe,
            "payload_passthrough_family_count": len(payload_passthrough_remaining),
            "payload_passthrough_families": payload_passthrough_remaining,
        },
        "variant_contracts": {
            "dkkd_variant_keys": [item["variant_key"] for item in dkkd_variants.get("variants", [])],
            "bbtd_variant_keys": [item["variant_key"] for item in bbtd_variants.get("variants", [])],
        },
        "ddkd_appendix_decision_status": {
            "promotable_now": promotable_now,
            "blocked_fields": blocked_fields,
        },
        "remaining_follow_on": [
            "Real Explorer + Word + direct-save validation on private network in Phase 6",
            "Family-by-family promotion from payload_passthrough to explicit runtime contract",
            "Copy-forward parity for families that transplant prior bookmark/table content",
            "Explicit policy for tolerated missing-bookmark writes, if any are approved",
            "Excel-backed support-document branch adjudication outside the current Word render-safe baseline",
        ],
    }


def render_markdown(summary: dict[str, Any]) -> str:
    baseline = summary["document_generation_baseline"]
    runtime = summary["runtime_contract_status"]
    appendix = summary["ddkd_appendix_decision_status"]
    variants = summary["variant_contracts"]
    lines = [
        "# Phase 5 Final Closeout",
        "",
        "Generated by `tools/build_phase5_final_closeout.py`.",
        "",
        "## Status",
        "",
        f"- Phase 5 status: `{summary['phase5_status']}`",
        f"- Registry families: `{baseline['registry_family_count']}`",
        f"- Matched active families: `{baseline['matched_family_count']}`",
        f"- Active template files audited: `{baseline['active_template_file_count']}`",
        f"- PowerPoint branch in scope: `{baseline['powerpoint_branch_in_scope']}`",
        "",
        "## Runtime Contract Status",
        "",
        "- `contract_exact` scalar families: "
        + ", ".join(f"`{item}`" for item in runtime["contract_exact_scalar_families"]),
        "- `contract_variant_exact` families: "
        + ", ".join(f"`{item}`" for item in runtime["contract_variant_exact_families"]),
        "- selection-safe families: "
        + ", ".join(f"`{item}`" for item in runtime["selection_safe_families"]),
        f"- payload-passthrough families remaining: `{runtime['payload_passthrough_family_count']}`",
        "",
        "## Variant Contracts",
        "",
        "- DDKD variants: " + ", ".join(f"`{item}`" for item in variants["dkkd_variant_keys"]),
        "- BBTD variants: " + ", ".join(f"`{item}`" for item in variants["bbtd_variant_keys"]),
        "",
        "## DDKD Appendix/Decision",
        "",
        "- promotable now: " + ", ".join(f"`{item}`" for item in appendix["promotable_now"]),
        "- still blocked: " + ", ".join(f"`{item}`" for item in appendix["blocked_fields"]),
        "",
        "## Follow-on",
        "",
    ]
    for item in summary["remaining_follow_on"]:
        lines.append(f"- {item}")
    return "\n".join(lines) + "\n"


def main() -> int:
    summary = build_summary()
    JSON_OUT.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(render_markdown(summary), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
