from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "artifacts" / "phase7"
READINESS_PATH = OUT_DIR / "cutover_readiness.json"
CHECKLIST_PATH = OUT_DIR / "cutover_checklist_summary.json"
JSON_OUT = OUT_DIR / "phase7_final_closeout.json"
MD_OUT = OUT_DIR / "phase7_final_closeout.md"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_utf8(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def build_summary() -> dict[str, Any]:
    readiness = load_json(READINESS_PATH)
    checklist = load_json(CHECKLIST_PATH)
    return {
        "generated_on": "2026-08-14",
        "phase7_status": readiness["phase7_status"],
        "checklist_status": checklist["overall_status"],
        "blocked_gates": [
            gate_name
            for gate_name, payload in readiness["gates"].items()
            if payload["status"] == "blocked"
        ],
        "required_outstanding": checklist["required_outstanding"],
    }


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Phase 7 Final Closeout",
        "",
        "Generated by `tools/build_phase7_final_closeout.py`.",
        "",
        f"- Phase 7 status: `{summary['phase7_status']}`",
        f"- Checklist status: `{summary['checklist_status']}`",
        "",
        "## Blocked Gates",
        "",
    ]
    if not summary["blocked_gates"]:
        lines.append("- none")
    else:
        for item in summary["blocked_gates"]:
            lines.append(f"- `{item}`")
    lines.extend(["", "## Outstanding Required Checklist Items", ""])
    if not summary["required_outstanding"]:
        lines.append("- none")
    else:
        for item in summary["required_outstanding"]:
            lines.append(f"- `{item}`")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    summary = build_summary()
    _write_utf8(JSON_OUT, json.dumps(summary, ensure_ascii=False, indent=2) + "\n")
    _write_utf8(MD_OUT, render_markdown(summary))
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
