from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "artifacts" / "phase6"
ENV_PROBE = OUT_DIR / "environment_probe.json"
WORD_HARNESS = OUT_DIR / "word_desktop_harness.json"
SUMMARY = OUT_DIR / "desktop_validation_summary.json"
JSON_OUT = OUT_DIR / "phase6_final_closeout.json"
MD_OUT = OUT_DIR / "phase6_final_closeout.md"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def build_summary() -> dict[str, Any]:
    env_probe = load_json(ENV_PROBE)
    word_harness = load_json(WORD_HARNESS)
    validation = load_json(SUMMARY)
    return {
        "generated_on": "2026-08-14",
        "phase6_status": validation["overall_status"],
        "environment": {
            "word_com_available": env_probe.get("word_com", {}).get("available", False),
            "explorer_available": bool(env_probe.get("explorer_executable")),
            "tailscale_available": bool(env_probe.get("tailscale_executable")),
            "active_smb_mapping_count": len(env_probe.get("active_smb_mappings", [])),
            "disconnected_smb_mapping_count": len(env_probe.get("disconnected_smb_mappings", [])),
        },
        "local_word_harness": {
            "document_updated_text_verified": word_harness.get("document_updated_text_verified", False),
            "lock_behavior_observed": word_harness.get("lock_behavior_observed", False),
        },
        "required_outstanding": validation.get("required_outstanding", []),
    }


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Phase 6 Final Closeout",
        "",
        "Generated by `tools/build_phase6_final_closeout.py`.",
        "",
        "## Status",
        "",
        f"- Phase 6 status: `{summary['phase6_status']}`",
        f"- Word COM available: `{summary['environment']['word_com_available']}`",
        f"- Explorer available: `{summary['environment']['explorer_available']}`",
        f"- Tailscale available: `{summary['environment']['tailscale_available']}`",
        f"- Active SMB mappings: `{summary['environment']['active_smb_mapping_count']}`",
        f"- Disconnected SMB mappings: `{summary['environment']['disconnected_smb_mapping_count']}`",
        f"- Local Word edit/save harness verified: `{summary['local_word_harness']['document_updated_text_verified']}`",
        "",
        "## Outstanding Required Scenarios",
        "",
    ]
    if not summary["required_outstanding"]:
        lines.append("- none")
    else:
        for item in summary["required_outstanding"]:
            lines.append(f"- `{item}`")
    return "\n".join(lines) + "\n"


def main() -> int:
    summary = build_summary()
    JSON_OUT.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(render_markdown(summary), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
