from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
PHASE2_RECON_PATH = ROOT / "artifacts" / "phase2" / "reconciliation.json"
PHASE3P_CONFLICTS_PATH = ROOT / "artifacts" / "phase3p" / "current_projection_conflicts.json"
PHASE3Q_BLANKED_PATH = ROOT / "artifacts" / "phase3q" / "confirmed_blanked_rows.json"
OUT_DIR = ROOT / "artifacts" / "phase3r"
JSON_OUT = OUT_DIR / "phase3_final_closeout.json"
MD_OUT = OUT_DIR / "phase3_final_closeout.md"


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def build_summary() -> dict[str, Any]:
    phase2 = load_json(PHASE2_RECON_PATH)
    phase3p = load_json(PHASE3P_CONFLICTS_PATH)
    phase3q = load_json(PHASE3Q_BLANKED_PATH)

    anomaly_rows = phase2.get("anomaly_rows", [])

    return {
        "generated_on": "2026-08-14",
        "phase3_status": "closed",
        "structured_import_baseline": {
            "total_anomalies": len(anomaly_rows),
            "open_anomalies": sum(1 for row in anomaly_rows if row.get("status") == "open"),
            "overridden_anomalies": sum(1 for row in anomaly_rows if row.get("status") == "overridden"),
            "excluded_confirmed_blanked_anomalies": sum(
                1 for row in anomaly_rows if row.get("status") == "excluded_confirmed_blanked"
            ),
            "effective_mismatch_count": len(phase2.get("effective_mismatches", {})),
            "excluded_rows": phase2.get("excluded_rows", {}),
        },
        "confirmed_blanked_scope": {
            "total_row_count": phase3q.get("total_row_count", 0),
            "by_sheet": {
                sheet: payload.get("row_count", 0)
                for sheet, payload in sorted((phase3q.get("by_sheet") or {}).items())
            },
        },
        "current_projection_conflicts": {
            "conflict_count": phase3p.get("conflict_count", 0),
            "manual_review_count": phase3p.get("manual_review_count", 0),
            "auto_resolvable_count": phase3p.get("auto_resolvable_count", 0),
            "projection_type_counts": phase3p.get("projection_type_counts", {}),
            "classification_counts": phase3p.get("classification_counts", {}),
        },
        "phase3_exit_criteria": {
            "structured_import_branch_closed": True,
            "confirmed_blanked_rows_excluded": True,
            "effective_import_mismatches_zero": len(phase2.get("effective_mismatches", {})) == 0,
            "remaining_work_moved_out_of_phase3": True,
        },
        "remaining_follow_on_work": [
            "Phase 4 storage integration and private-share execution path",
            "Phase 5 document/template fidelity and source/output lineage",
            "Current projection conflict adjudication beyond legacy import baseline",
        ],
    }


def render_markdown(summary: dict[str, Any]) -> str:
    structured = summary["structured_import_baseline"]
    conflicts = summary["current_projection_conflicts"]
    lines = [
        "# Phase 3 Final Closeout",
        "",
        "Generated by `tools/build_phase3r_final_closeout.py`.",
        "",
        "## Status",
        "",
        f"- Phase 3 status: `{summary['phase3_status']}`",
        f"- Total importer anomalies retained for audit: `{structured['total_anomalies']}`",
        f"- Open importer anomalies: `{structured['open_anomalies']}`",
        f"- Confirmed blanked exclusions: `{structured['excluded_confirmed_blanked_anomalies']}`",
        f"- Effective mismatch count: `{structured['effective_mismatch_count']}`",
        "",
        "## Structured Import Branch",
        "",
    ]
    for sheet, count in structured["excluded_rows"].items():
        lines.append(f"- `{sheet}` excluded confirmed blanked rows: `{count}`")

    lines.extend(
        [
            "",
            "## Conflict Branch",
            "",
            f"- Current projection conflicts: `{conflicts['conflict_count']}`",
            f"- Manual review required: `{conflicts['manual_review_count']}`",
            f"- Auto-resolvable: `{conflicts['auto_resolvable_count']}`",
            "",
            "## Exit Criteria",
            "",
        ]
    )
    for key, value in summary["phase3_exit_criteria"].items():
        lines.append(f"- `{key}`: `{value}`")

    lines.extend(["", "## Follow-on Work", ""])
    for item in summary["remaining_follow_on_work"]:
        lines.append(f"- {item}")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    summary = build_summary()
    JSON_OUT.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(render_markdown(summary), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
