from __future__ import annotations

from collections import Counter, defaultdict
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = ROOT / "artifacts" / "phase3_review" / "anomaly_review_report.json"
OUT_DIR = ROOT / "artifacts" / "phase3q"
JSON_OUT = OUT_DIR / "confirmed_blanked_rows.json"
MD_OUT = OUT_DIR / "confirmed_blanked_rows.md"


CONFIRMATION_NOTE = (
    "Confirmed by business owner on 2026-08-14: rows in anomaly_review_report are intended deletions "
    "that were blanked in-place instead of physically removed because legacy Excel INDEX-based formulas "
    "still depend on row positions."
)


def load_rows() -> list[dict[str, Any]]:
    return json.loads(INPUT_PATH.read_text(encoding="utf-8"))


def build_manifest(rows: list[dict[str, Any]]) -> dict[str, Any]:
    by_sheet: dict[str, list[dict[str, Any]]] = defaultdict(list)
    by_reason = Counter()

    for row in rows:
        sheet = row["source_sheet"]
        by_sheet[sheet].append(row)
        by_reason[row["reason"]] += 1

    manifest_rows = []
    for row in rows:
        manifest_rows.append(
            {
                "source_sheet": row["source_sheet"],
                "source_row_key": row["source_row_key"],
                "source_row_number": row.get("source_row_number"),
                "legacy_row_id": row.get("legacy_row_id"),
                "reason": row["reason"],
                "required_field": row.get("required_field"),
                "raw_fk_value": row.get("raw_fk_value"),
                "classification": "confirmed_blanked_row",
                "migration_action": "exclude_from_business_import",
                "retention_policy": "keep_legacy_row_position_only",
                "confirmation_source": "user_review_of_anomaly_report",
                "confirmed_on": "2026-08-14",
                "confirmation_note": CONFIRMATION_NOTE,
            }
        )

    per_sheet = {}
    for sheet, sheet_rows in sorted(by_sheet.items()):
        per_sheet[sheet] = {
            "row_count": len(sheet_rows),
            "source_row_keys": [row["source_row_key"] for row in sheet_rows],
            "legacy_row_ids": [
                str(row["legacy_row_id"]).strip()
                for row in sheet_rows
                if str(row.get("legacy_row_id") or "").strip()
            ],
            "reason_counts": dict(sorted(Counter(row["reason"] for row in sheet_rows).items())),
        }

    return {
        "generated_on": "2026-08-14",
        "input_path": str(INPUT_PATH.relative_to(ROOT)),
        "confirmation_source": "user_review_of_anomaly_report",
        "confirmation_scope": "all rows currently present in artifacts/phase3_review/anomaly_review_report.json",
        "confirmation_note": CONFIRMATION_NOTE,
        "total_row_count": len(rows),
        "by_reason": dict(sorted(by_reason.items())),
        "by_sheet": per_sheet,
        "rows": manifest_rows,
    }


def render_markdown(manifest: dict[str, Any]) -> str:
    lines = [
        "# Confirmed Blanked Rows",
        "",
        "Generated by `tools/build_phase3q_confirmed_blanked_rows.py`.",
        "",
        "## Confirmation",
        "",
        f"- Scope: `{manifest['confirmation_scope']}`",
        f"- Confirmed on: `{manifest['generated_on']}`",
        f"- Total rows: `{manifest['total_row_count']}`",
        f"- Note: {manifest['confirmation_note']}",
        "",
        "## By reason",
        "",
    ]

    for reason, count in manifest["by_reason"].items():
        lines.append(f"- `{reason}`: `{count}`")

    lines.extend(["", "## By sheet", ""])
    for sheet, payload in manifest["by_sheet"].items():
        lines.append(f"- `{sheet}`: `{payload['row_count']}` rows")
        reason_text = ", ".join(f"{reason}={count}" for reason, count in payload["reason_counts"].items())
        lines.append(f"- reason counts: `{reason_text}`")

    lines.extend(
        [
            "",
            "## Migration implication",
            "",
            "- Treat these rows as confirmed blanked placeholders, not unresolved business anomalies.",
            "- Exclude them from target business-entity import.",
            "- Preserve only replay/audit references if needed for reconciliation history.",
            "- Do not spend external-evidence review effort on this set.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    rows = load_rows()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    manifest = build_manifest(rows)
    JSON_OUT.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(render_markdown(manifest), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
