from __future__ import annotations

from collections import Counter
import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
INPUT_PATH = ROOT / "artifacts" / "legacy_audit" / "duplicate_current_analysis.json"
OUT_DIR = ROOT / "artifacts" / "phase3p"
JSON_OUT = OUT_DIR / "current_projection_conflicts.json"
MD_OUT = OUT_DIR / "current_projection_conflicts.md"


def load_analysis() -> dict[str, Any]:
    return json.loads(INPUT_PATH.read_text(encoding="utf-8"))


def build_resolution_policy(source_name: str, classification: str) -> tuple[str, str]:
    if source_name == "db_cc" and classification == "blank_ma_dc_non_case_backed_multi_current":
        return (
            "manual_review_required",
            "Multiple non-case-backed certificate rows collapse onto one current key when MÃ DC is blank; no proven business discriminator exists yet.",
        )
    if source_name == "db_ktra" and classification == "completed_plus_pending_both_current":
        return (
            "manual_review_required",
            "One completed row and one pending row are both marked current; workbook evidence does not yet prove which row should drive the target current-case projection.",
        )
    if source_name == "db_ktra" and classification == "multiple_completed_both_current":
        return (
            "manual_review_required",
            "More than one completed inspection row remains current; no proven winner-selection rule exists yet.",
        )
    return (
        "manual_review_required",
        "No approved auto-resolution rule exists for this current-projection conflict class.",
    )


def projection_type_for(source_name: str) -> str:
    if source_name == "db_cc":
        return "current_certificate_projection"
    if source_name == "db_ktra":
        return "current_case_projection"
    raise ValueError(f"Unsupported source group: {source_name}")


def source_sheet_for(source_name: str) -> str:
    if source_name == "db_cc":
        return "db.cc"
    if source_name == "db_ktra":
        return "db.ktra"
    raise ValueError(f"Unsupported source group: {source_name}")


def candidate_ids(group: dict[str, Any]) -> list[str]:
    return [str(row.get("legacy_row_id", "")).strip() for row in group.get("rows", []) if str(row.get("legacy_row_id", "")).strip()]


def build_conflict_detail(source_name: str, group: dict[str, Any]) -> dict[str, Any]:
    if source_name == "db_cc":
        return {
            "all_blank_ma_dc": group.get("all_blank_ma_dc", False),
            "all_blank_inspection_id": group.get("all_blank_inspection_id", False),
            "unique_site_ids": group.get("unique_site_ids", []),
            "unique_certificate_nos": group.get("unique_certificate_nos", []),
        }
    progress_values = []
    linked_certificate_ids = []
    for row in group.get("rows", []):
        progress = str(row.get("progress", "")).strip()
        linked_certificate_id = str(row.get("linked_certificate_id", "")).strip()
        if progress:
            progress_values.append(progress)
        if linked_certificate_id:
            linked_certificate_ids.append(linked_certificate_id)
    return {
        "progress_values": progress_values,
        "linked_certificate_ids": linked_certificate_ids,
    }


def build_conflict_rows(report: dict[str, Any]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for source_name in ("db_cc", "db_ktra"):
        for group in report[source_name]["groups"]:
            policy, rationale = build_resolution_policy(source_name, group["classification"])
            conflict = {
                "conflict_key": f"{source_sheet_for(source_name)}::{group['lookup_key']}",
                "projection_type": projection_type_for(source_name),
                "source_sheet": source_sheet_for(source_name),
                "business_key": group["lookup_key"],
                "classification": group["classification"],
                "resolution_policy": policy,
                "status": "open",
                "detected_on": "2026-08-14",
                "candidate_count": group["row_count"],
                "candidate_legacy_ids": candidate_ids(group),
                "resolution_rationale": rationale,
                "detail": build_conflict_detail(source_name, group),
            }
            rows.append(conflict)
    rows.sort(key=lambda row: (row["projection_type"], row["business_key"]))
    return rows


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Current Projection Conflicts",
        "",
        "Generated by `tools/build_phase3p_current_projection_conflicts.py`.",
        "",
        "## Summary",
        "",
        f"- Total conflicts: `{summary['conflict_count']}`",
        f"- Auto-resolvable conflicts: `{summary['auto_resolvable_count']}`",
        f"- Manual-review conflicts: `{summary['manual_review_count']}`",
        "",
        "## By projection type",
        "",
    ]
    for key, count in summary["projection_type_counts"].items():
        lines.append(f"- `{key}`: `{count}`")

    lines.extend(["", "## By classification", ""])
    for key, count in summary["classification_counts"].items():
        lines.append(f"- `{key}`: `{count}`")

    lines.extend(["", "## Conflicts", ""])
    for row in summary["conflicts"]:
        lines.append(
            f"- `{row['conflict_key']}` -> `{row['classification']}` / `{row['resolution_policy']}` / `{row['candidate_count']}` candidates"
        )
        lines.append(f"- candidates: `{', '.join(row['candidate_legacy_ids'])}`")
        lines.append(f"- rationale: {row['resolution_rationale']}")

    return "\n".join(lines) + "\n"


def build_summary() -> dict[str, Any]:
    report = load_analysis()
    conflicts = build_conflict_rows(report)
    projection_type_counts = Counter(row["projection_type"] for row in conflicts)
    classification_counts = Counter(row["classification"] for row in conflicts)
    manual_review_count = sum(1 for row in conflicts if row["resolution_policy"] == "manual_review_required")
    auto_resolvable_count = sum(1 for row in conflicts if row["resolution_policy"] != "manual_review_required")
    return {
        "generated_on": "2026-08-14",
        "input_path": str(INPUT_PATH.relative_to(ROOT)),
        "conflict_count": len(conflicts),
        "auto_resolvable_count": auto_resolvable_count,
        "manual_review_count": manual_review_count,
        "projection_type_counts": dict(sorted(projection_type_counts.items())),
        "classification_counts": dict(sorted(classification_counts.items())),
        "conflicts": conflicts,
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    summary = build_summary()
    JSON_OUT.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(render_markdown(summary), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
