from __future__ import annotations

import json
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "artifacts" / "phase4"
JSON_OUT = OUT_DIR / "phase4_final_closeout.json"
MD_OUT = OUT_DIR / "phase4_final_closeout.md"


def build_summary() -> dict[str, Any]:
    return {
        "generated_on": "2026-08-14",
        "phase4_status": "closed",
        "storage_capabilities": {
            "inspection_binding_first_lookup": True,
            "inspection_fail_closed_resolution": True,
            "dkkd_site_token_resolution": True,
            "path_traversal_protection": True,
            "root_boundary_enforcement": True,
            "read_only_probe_endpoints": [
                "/storage/inspection-folder",
                "/storage/dkkd-folder",
            ],
            "probe_cli": "tools/probe_phase4_storage_nonprod.py",
        },
        "ddkd_contract": {
            "resolver_key": "(<site_id>)",
            "display_name_is_identity": False,
            "issuance_cycle_folder_is_identity": False,
            "binding_persistence_in_scope": False,
        },
        "remaining_operational_follow_on": [
            "Non-production private-share execution evidence over Tailscale or equivalent private transport",
            "Inspector desktop workflow validation with Windows Explorer and Microsoft Word direct save",
            "Network interruption and file-lock behavior under real NAS conditions",
        ],
    }


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Phase 4 Final Closeout",
        "",
        "Generated by `tools/build_phase4g_final_closeout.py`.",
        "",
        "## Status",
        "",
        f"- Phase 4 status: `{summary['phase4_status']}`",
        f"- Inspection binding-first lookup: `{summary['storage_capabilities']['inspection_binding_first_lookup']}`",
        f"- Inspection fail-closed resolution: `{summary['storage_capabilities']['inspection_fail_closed_resolution']}`",
        f"- DDKD site-token resolution: `{summary['storage_capabilities']['dkkd_site_token_resolution']}`",
        f"- Path traversal protection: `{summary['storage_capabilities']['path_traversal_protection']}`",
        "",
        "## DDKD Contract",
        "",
        f"- Resolver key: `{summary['ddkd_contract']['resolver_key']}`",
        f"- Display name is identity: `{summary['ddkd_contract']['display_name_is_identity']}`",
        f"- `Lần n` folder is identity: `{summary['ddkd_contract']['issuance_cycle_folder_is_identity']}`",
        f"- DDKD binding persistence in scope: `{summary['ddkd_contract']['binding_persistence_in_scope']}`",
        "",
        "## Read-Only Probe Surface",
        "",
    ]
    for path in summary["storage_capabilities"]["read_only_probe_endpoints"]:
        lines.append(f"- `{path}`")
    lines.extend(["", "## Operational Follow-on", ""])
    for item in summary["remaining_operational_follow_on"]:
        lines.append(f"- {item}")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    summary = build_summary()
    JSON_OUT.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")
    MD_OUT.write_text(render_markdown(summary), encoding="utf-8")
    print(f"Wrote {JSON_OUT}")
    print(f"Wrote {MD_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
