from __future__ import annotations

import json
import argparse
import sys
from pathlib import Path
from typing import Any

from tools.phase7_execution_evidence import (
    Phase7ExecutionEvidenceError,
    require_execution_evidence,
)



def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def _write_utf8(path: Path, content: str) -> None:
    path.write_text(content, encoding="utf-8", newline="\n")


def build_summary(*, evidence_dir: Path) -> dict[str, Any]:
    evidence_paths = require_execution_evidence(evidence_dir)
    readiness = load_json(evidence_paths.readiness_json_path)
    checklist = load_json(evidence_paths.checklist_summary_json_path)
    operational_pack = load_json(evidence_paths.operational_pack_json_path)
    return {
        "generated_on": "2026-08-26",
        "phase7_status": readiness["phase7_status"],
        "checklist_status": checklist["overall_status"],
        "blocked_gates": [
            gate_name
            for gate_name, payload in readiness["gates"].items()
            if payload["status"] == "blocked"
        ],
        "required_outstanding": checklist["required_outstanding"],
        "operational_pack_status": operational_pack["checklist_status"],
    }


def render_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Phase 7 Final Closeout",
        "",
        "Generated by `tools/build_phase7_final_closeout.py`.",
        "",
        f"- Phase 7 status: `{summary['phase7_status']}`",
        f"- Checklist status: `{summary['checklist_status']}`",
        "",
        "## Blocked Gates",
        "",
    ]
    if not summary["blocked_gates"]:
        lines.append("- none")
    else:
        for item in summary["blocked_gates"]:
            lines.append(f"- `{item}`")
    lines.extend(["", "## Outstanding Required Checklist Items", ""])
    if not summary["required_outstanding"]:
        lines.append("- none")
    else:
        for item in summary["required_outstanding"]:
            lines.append(f"- `{item}`")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build Phase 7 final closeout from external execution evidence.")
    parser.add_argument("--evidence-dir", required=True, type=Path)
    args = parser.parse_args(argv)
    try:
        evidence_paths = require_execution_evidence(args.evidence_dir)
        summary = build_summary(evidence_dir=args.evidence_dir)
    except (Phase7ExecutionEvidenceError, OSError, ValueError, KeyError, json.JSONDecodeError, TypeError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    _write_utf8(evidence_paths.final_closeout_json_path, json.dumps(summary, ensure_ascii=False, indent=2) + "\n")
    _write_utf8(evidence_paths.final_closeout_markdown_path, render_markdown(summary))
    print(f"Wrote {evidence_paths.final_closeout_json_path}")
    print(f"Wrote {evidence_paths.final_closeout_markdown_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
